# Generated by Django 5.1.6 on 2025-03-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_catagory_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='feature',
        ),
    ]
