# Generated by Django 5.1.6 on 2025-03-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
    ]
