# Generated by Django 5.1.6 on 2025-04-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_payment_id_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_selected/'),
        ),
    ]
