# Generated by Django 5.1.6 on 2025-04-08 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_item', to='store.variant'),
        ),
    ]
