# Generated by Django 5.1.6 on 2025-04-08 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_variantitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_items', to='store.variant'),
        ),
    ]
