# Generated by Django 5.1.6 on 2025-04-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_cart_variant_image_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/'),
        ),
    ]
