# Generated by Django 5.1.6 on 2025-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cid',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
