# Generated by Django 5.1.6 on 2025-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_category_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
