# Generated by Django 5.1.6 on 2025-08-21 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_category_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='images/product.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('refund', 'Refund'), ('reorder', 'Reorder')], max_length=20, null=True)),
                ('refund_upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('refund_bank_account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('refund_bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='store.order')),
            ],
        ),
    ]
